# Generated by Django 3.1 on 2020-08-13 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20200813_0952'),
        ('registro_dejep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodejep',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
